Update compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,48 +1,78 @@
-#!/bin/sh
+#!/usr/bin/env bash
+# bin/compile <build-dir> <cache-dir>
 
-MONO3_VM_BINARY="http://s3.amazonaws.com/mono3-buildpack/mono-fsharp-nuget3.0.tar.bz2"
-NUGET_BINARY="http://s3.amazonaws.com/mono3-buildpack/nuget.tar.bz2"
+# fail fast
+set -e
+
+DEPENDENCY_S3_BUCKET_PATH="http://s3.amazonaws.com/mono-dependencies"
+MONO_VERSION="3.10.0"
 PAKET_BINARY="https://github.com/fsprojects/Paket/releases/download/0.27.2/paket.exe"
-MONO3_VM_VENDOR="vendor/"
+NUGET_BINARY="http://nuget.org/nuget.exe"
 
-NUGET="$1/$MONO3_VM_VENDOR/mono3/bin/NuGet.exe"
-MOZROOT="$1/$MONO3_VM_VENDOR/mono3/lib/mono/4.5/mozroots.exe"
-XBUILD="$1/$MONO3_VM_VENDOR/mono3/lib/mono/4.5/xbuild.exe"
+BUILD_DIR=$1
+CACHE_DIR=$2
 
-echo "-----> Copying mono to $1/$MONO3_VM_VENDOR"
-mkdir -p "$1/$MONO3_VM_VENDOR"
-curl $MONO3_VM_BINARY -o - | tar xj -C "$1/$MONO3_VM_VENDOR" -f -
-curl $NUGET_BINARY -o - | tar xj -C "$1/$MONO3_VM_VENDOR/mono3/bin/" -f -
-wget -O "$1/$MONO3_VM_VENDOR/mono3/bin/paket.exe" $PAKET_BINARY
+function conditional_download() {
+  DOWNLOAD_URL="$1"
+  DESTINATION="$2"
 
-echo "#!/bin/sh\n$1/$MONO3_VM_VENDOR/mono3/bin/mono $1/$MONO3_VM_VENDOR/mono3/lib/mono/4.5/fsc.exe \"\$@\"" > $1/$MONO3_VM_VENDOR/mono3/bin/fsharpc-heroku
-echo "#!/bin/sh\n/app/vendor/mono3/bin/mono /app/vendor/mono3/lib/mono/4.5/fsi.exe \"\$@\"" > $1/$MONO3_VM_VENDOR/mono3/bin/fsharpi-heroku
-chmod +x $1/$MONO3_VM_VENDOR/mono3/bin/fsharpc-heroku
-chmod +x $1/$MONO3_VM_VENDOR/mono3/bin/fsharpi-heroku
+  if [ ! -d ${DESTINATION} ]; then
+    rm -rf ${DESTINATION}
+    mkdir -p ${DESTINATION}
+    echo "-----> Downloading ${DOWNLOAD_URL}"
+    curl ${DOWNLOAD_URL} -s | tar xz -C ${DESTINATION}
+  fi
+}
 
-echo "-----> Setting envvars"
-export PATH="$PATH:$1/$MONO3_VM_VENDOR/mono3/bin"
-export LD_LIBRARY_PATH="$1/$MONO3_VM_VENDOR/mono3/lib"
+LP_DIR=`cd $(dirname $0); cd ..; pwd`
+cd ${BUILD_DIR}
+mkdir -p ${CACHE_DIR}
+
+MONO_CACHE_LOCATION=${CACHE_DIR}/$STACK/mono-${MONO_VERSION}
+conditional_download ${DEPENDENCY_S3_BUCKET_PATH}/${STACK}/mono-${MONO_VERSION}.tar.gz ${MONO_CACHE_LOCATION}
+
+
+# Copy mono from cache to where we're building the slug
+cp -r "${MONO_CACHE_LOCATION}/mono" .
+# Mono expects to be running out of /app
+ln -s "$BUILD_DIR/mono" /app
+
+
+NUGET_EXECUTABLE_PATH=${CACHE_DIR}/nuget.exe
+PAKET_EXECUTABLE_PATH=${CACHE_DIR}/paket.exe
+
+if [ ! -f ${PAKET_EXECUTABLE_PATH} ]; then
+  curl -LSso PAKET_EXECTABLE_PATH $PAKET_BINARY
+fi
+
+if [ ! -f ${NUGET_EXECUTABLE_PATH} ]; then
+  curl -LSso ${NUGET_EXECUTABLE_PATH} $NUGET_BINARY
+fi
+
+
+export PATH="/app/mono/bin:${PATH}"
+export LD_LIBRARY_PATH="/app/mono/lib:${LD_LIBRARY_PATH}"
+
 echo "-----> Importing trusted root certificates"
-mono $MOZROOT --sync --import
+mozroots --sync --import
 cd $1
 
 if [ -f paket.dependencies ]; then
   echo "-----> paket.dependencies found, installing packages with paket"
-  mono $MONO3_VM_VENDOR/mono3/bin/paket.exe install
+  mono $PAKET_EXECUTABLE_PATH install
 fi
 
 if [ -f packages.config -o -f */packages.config ]; then 
    echo "-----> packages.config found, installing dependencies with nuget" 
-   find  -name packages.config | xargs mono $NUGET install -o packages 
+   find  -name packages.config | xargs mono $NUGET_EXECUTABLE_PATH restore -NonInteractive 
 fi 
 
 if [ -f app.fsx ]; then
   echo "-----> Compiling app.fsx"
-  fsharpc-heroku app.fsx
+  fsharpc app.fsx
 fi
 
 if [ -f *.sln -a ! -f dummy.sln]; then
    echo "-----> Compiling application" 
-   mono $XBUILD /property:FscToolExe="$1/$MONO3_VM_VENDOR/mono3/bin/fsharpc-heroku" 
+   xbuild 
 fi
